In [75]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
house = pd.read_csv("housing_price.csv")
house

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                  15         5612            1283   
1        -114.47     34.40                  19         7650            1901   
2        -114.56     33.69                  17          720             174   
3        -114.57     33.64                  14         1501             337   
4        -114.57     33.57                  20         1454             326   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                  52         2217             394   
16996    -124.27     40.69                  36         2349             528   
16997    -124.30     41.84                  17         2677             531   
16998    -124.30     41.80                  19         2672             552   
16999    -124.35     40.54                  52         1820             300   

       population  households  median_income  median_house_value  
0            1015         472         1.4936               66900  
1            1129         463         1.8200               80100  
2             333         117         1.6509               85700  
3             515         226         3.1917               73400  
4             624         262         1.9250               65500  
...           ...         ...            ...                 ...  
16995         907         369         2.3571              111400  
16996        1194         465         2.5179               79000  
16997        1244         456         3.0313              103600  
16998        1298         478         1.9797               85800  
16999         806         270         3.0147               94600  

[17000 rows x 9 columns]

In [76]:
house.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [77]:
new_house = house.dropna()
new_house

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                  15         5612            1283   
1        -114.47     34.40                  19         7650            1901   
2        -114.56     33.69                  17          720             174   
3        -114.57     33.64                  14         1501             337   
4        -114.57     33.57                  20         1454             326   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                  52         2217             394   
16996    -124.27     40.69                  36         2349             528   
16997    -124.30     41.84                  17         2677             531   
16998    -124.30     41.80                  19         2672             552   
16999    -124.35     40.54                  52         1820             300   

       population  households  median_income  median_house_value  
0            1015         472         1.4936               66900  
1            1129         463         1.8200               80100  
2             333         117         1.6509               85700  
3             515         226         3.1917               73400  
4             624         262         1.9250               65500  
...           ...         ...            ...                 ...  
16995         907         369         2.3571              111400  
16996        1194         465         2.5179               79000  
16997        1244         456         3.0313              103600  
16998        1298         478         1.9797               85800  
16999         806         270         3.0147               94600  

[17000 rows x 9 columns]

In [78]:
x = new_house[["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income"]].values
print("independent data",x)
y = new_house['median_house_value'].values
print("dependent data",y)

independent data [[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]
dependent data [ 66900  80100  85700 ... 103600  85800  94600]


In [79]:
x =new_house.drop("median_house_value",axis = 1)
print("independent data",x)
y = new_house['median_house_value'].values
print("dependent data",y)

independent data        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                  15         5612            1283   
1        -114.47     34.40                  19         7650            1901   
2        -114.56     33.69                  17          720             174   
3        -114.57     33.64                  14         1501             337   
4        -114.57     33.57                  20         1454             326   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                  52         2217             394   
16996    -124.27     40.69                  36         2349             528   
16997    -124.30     41.84                  17         2677             531   
16998    -124.30     41.80                  19         2672             552   
16999    -124.35     40.54                  52         1820             300   

       population  households  med

In [80]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)
print("X_train and x_test dataset shape",(X_train.shape),(X_test.shape))
print("y_train and y_test dataset shape",(y_train.shape),(y_test.shape))

X_train and x_test dataset shape (13600, 8) (3400, 8)
y_train and y_test dataset shape (13600,) (3400,)


In [81]:
from sklearn.metrics import r2_score
X =new_house.drop("median_house_value",axis = 1)
y = new_house['median_house_value'].values
reg = LinearRegression()
reg.fit(X, y)
reg.score(X,y)
print("r value is",reg.score(X,y))
print("reg.coefficient is",reg.coef_)
print("intercept is",reg.intercept_)

r value is 0.6413378529502689
reg.coefficient is [-4.31396373e+04 -4.29256731e+04  1.15069493e+03 -8.37825121e+00
  1.17648543e+02 -3.84887721e+01  4.54360026e+01  4.05070684e+04]
intercept is -3620600.892973681


In [82]:
y_pred = reg.predict(X_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df.head(9)

Actual      Predicted
0   96100   -6796.508337
1  500001  492229.306377
2  177200  112016.437980
3   55000  217153.503244
4  220800  207687.743759
5  158300  121037.071021
6   37900  180273.940338
7  115600  103832.477394
8  359700  311057.178134

In [83]:
X = new_house.drop("median_house_value",axis = 1).values
y = new_house['median_house_value'].values
X2 = sm.add_constant(X)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.641
Model:                            OLS   Adj. R-squared:                  0.641
Method:                 Least Squares   F-statistic:                     3798.
Date:                Fri, 12 Aug 2022   Prob (F-statistic):               0.00
Time:                        12:41:57   Log-Likelihood:            -2.1365e+05
No. Observations:               17000   AIC:                         4.273e+05
Df Residuals:                   16991   BIC:                         4.274e+05
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.621e+06   6.92e+04    -52.312      0.0